import Head from 'next/head';
import { PageContainer } from 'styles/index.css';

import ArrayComponent, { peopleData } from 'src/sections/ArrayTest/ArrayComponent';

const Home = (): JSX.Element => (
  <>
    <Head>
      <title>Project Starter</title>
      <meta content="Generated by create next app" name="description" />
      <link href="/favicon.ico" rel="icon" />
    </Head>

    <main className={PageContainer}>
      <ArrayComponent data={peopleData}/>
    </main>
  </>
);
export default Home;
